# fly.toml app configuration file generated for dans-todos on 2023-06-30T20:12:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dans-todos"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  builder = "heroku/buildpacks:20"
  [build.args]
    VITE_CLIENT_ID = "368363262826-i6ngmdb856kpnjnj3huu2bpnaoiisf3h.apps.googleusercontent.com"
    VITE_SESSION_MAX_AGE = "604800000"

[env]
  PORT = "8080"
  VITE_CLIENT_ID = "368363262826-i6ngmdb856kpnjnj3huu2bpnaoiisf3h.apps.googleusercontent.com"
  VITE_SESSION_MAX_AGE = "604800000"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
