CREATE TABLE "User" (
  id VARCHAR(25) PRIMARY KEY NOT NULL
);

CREATE TABLE "Todo" ( 
  id SERIAL PRIMARY KEY NOT NULL,
  createdat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  text TEXT NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  userid VARCHAR(25) NOT NULL,
  FOREIGN KEY ("userid") REFERENCES "User"(id)
 );
