/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../context"
import type { core, connectionPluginCore } from "nexus"

declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName>
    ): void
  }
}
declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BoolFieldUpdateOperationsInput: { // input type
    set?: boolean | null; // Boolean
  }
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  TodoCreateInput: { // input type
    completed?: boolean | null; // Boolean
    createdat?: NexusGenScalars['DateTime'] | null; // DateTime
    text: string; // String!
  }
  TodoListRelationFilter: { // input type
    every?: NexusGenInputs['TodoWhereInput'] | null; // TodoWhereInput
    none?: NexusGenInputs['TodoWhereInput'] | null; // TodoWhereInput
    some?: NexusGenInputs['TodoWhereInput'] | null; // TodoWhereInput
  }
  TodoUpdateInput: { // input type
    completed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    createdat?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    text?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    user?: NexusGenInputs['UserUpdateOneRequiredWithoutTodosInput'] | null; // UserUpdateOneRequiredWithoutTodosInput
  }
  TodoUpdateManyMutationInput: { // input type
    completed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    createdat?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    text?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  TodoWhereInput: { // input type
    AND?: NexusGenInputs['TodoWhereInput'][] | null; // [TodoWhereInput!]
    NOT?: NexusGenInputs['TodoWhereInput'][] | null; // [TodoWhereInput!]
    OR?: NexusGenInputs['TodoWhereInput'][] | null; // [TodoWhereInput!]
    completed?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    createdat?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    text?: NexusGenInputs['StringFilter'] | null; // StringFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    userid?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  TodoWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  UserCreateOrConnectWithoutTodosInput: { // input type
    create: NexusGenInputs['UserCreateWithoutTodosInput']; // UserCreateWithoutTodosInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateWithoutTodosInput: { // input type
    id: string; // String!
  }
  UserUpdateOneRequiredWithoutTodosInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutTodosInput'] | null; // UserCreateOrConnectWithoutTodosInput
    create?: NexusGenInputs['UserCreateWithoutTodosInput'] | null; // UserCreateWithoutTodosInput
    update?: NexusGenInputs['UserUpdateWithoutTodosInput'] | null; // UserUpdateWithoutTodosInput
    upsert?: NexusGenInputs['UserUpsertWithoutTodosInput'] | null; // UserUpsertWithoutTodosInput
  }
  UserUpdateWithoutTodosInput: { // input type
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserUpsertWithoutTodosInput: { // input type
    create: NexusGenInputs['UserCreateWithoutTodosInput']; // UserCreateWithoutTodosInput!
    update: NexusGenInputs['UserUpdateWithoutTodosInput']; // UserUpdateWithoutTodosInput!
  }
  UserWhereInput: { // input type
    AND?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    NOT?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    OR?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    todos?: NexusGenInputs['TodoListRelationFilter'] | null; // TodoListRelationFilter
  }
  UserWhereUniqueInput: { // input type
    id?: string | null; // String
  }
}

export interface NexusGenEnums {
  Filter: "ACTIVE" | "ALL" | "COMPLETED"
  QueryMode: "default" | "insensitive"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  AffectedRowsOutput: { // root type
    count: number; // Int!
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  Query: {};
  Todo: { // root type
    completed: boolean; // Boolean!
    text: string; // String!
  }
  TodoEdge: { // root type
    cursor: string; // String!
    node: NexusGenRootTypes['Todo']; // Todo!
  }
  User: {};
  UserTodos_Connection: { // root type
    edges: NexusGenRootTypes['TodoEdge'][]; // [TodoEdge!]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AffectedRowsOutput: { // field return type
    count: number; // Int!
  }
  Mutation: { // field return type
    createOneTodo: NexusGenRootTypes['Todo']; // Todo!
    deleteManyTodo: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    deleteOneTodo: NexusGenRootTypes['Todo'] | null; // Todo
    updateManyTodo: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    updateOneTodo: NexusGenRootTypes['Todo'] | null; // Todo
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Query: { // field return type
    viewer: NexusGenRootTypes['User']; // User!
  }
  Todo: { // field return type
    completed: boolean; // Boolean!
    id: string; // ID!
    ownId: number; // Int!
    text: string; // String!
  }
  TodoEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Todo']; // Todo!
  }
  User: { // field return type
    id: string; // ID!
    todos: NexusGenRootTypes['UserTodos_Connection']; // UserTodos_Connection!
  }
  UserTodos_Connection: { // field return type
    completedCount: number; // Int!
    edges: NexusGenRootTypes['TodoEdge'][]; // [TodoEdge!]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
    totalCount: number; // Int!
  }
}

export interface NexusGenFieldTypeNames {
  AffectedRowsOutput: { // field return type name
    count: 'Int'
  }
  Mutation: { // field return type name
    createOneTodo: 'Todo'
    deleteManyTodo: 'AffectedRowsOutput'
    deleteOneTodo: 'Todo'
    updateManyTodo: 'AffectedRowsOutput'
    updateOneTodo: 'Todo'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  Query: { // field return type name
    viewer: 'User'
  }
  Todo: { // field return type name
    completed: 'Boolean'
    id: 'ID'
    ownId: 'Int'
    text: 'String'
  }
  TodoEdge: { // field return type name
    cursor: 'String'
    node: 'Todo'
  }
  User: { // field return type name
    id: 'ID'
    todos: 'UserTodos_Connection'
  }
  UserTodos_Connection: { // field return type name
    completedCount: 'Int'
    edges: 'TodoEdge'
    pageInfo: 'PageInfo'
    totalCount: 'Int'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneTodo: { // args
      data: NexusGenInputs['TodoCreateInput']; // TodoCreateInput!
    }
    deleteManyTodo: { // args
      where?: NexusGenInputs['TodoWhereInput'] | null; // TodoWhereInput
    }
    deleteOneTodo: { // args
      where: NexusGenInputs['TodoWhereUniqueInput']; // TodoWhereUniqueInput!
    }
    updateManyTodo: { // args
      data: NexusGenInputs['TodoUpdateManyMutationInput']; // TodoUpdateManyMutationInput!
      where?: NexusGenInputs['TodoWhereInput'] | null; // TodoWhereInput
    }
    updateOneTodo: { // args
      data: NexusGenInputs['TodoUpdateInput']; // TodoUpdateInput!
      where: NexusGenInputs['TodoWhereUniqueInput']; // TodoWhereUniqueInput!
    }
  }
  User: {
    todos: { // args
      after?: string | null; // String
      before?: string | null; // String
      filter: NexusGenEnums['Filter'] | null; // Filter
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}