/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as Context from "../context"



declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BoolFieldUpdateOperationsInput: { // input type
    set?: boolean | null; // Boolean
  }
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  QueryTodosWhereInput: { // input type
    completed?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  TodoCreateInput: { // input type
    completed: boolean; // Boolean!
    created_at?: NexusGenScalars['DateTime'] | null; // DateTime
    text: string; // String!
    updated_at?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  TodoOrderByInput: { // input type
    completed?: NexusGenEnums['SortOrder'] | null; // SortOrder
    created_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    text?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updated_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  TodoUpdateInput: { // input type
    completed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    created_at?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    text?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updated_at?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  TodoWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenRootTypes {
  Mutation: {};
  Query: {};
  Todo: { // root type
    completed: boolean; // Boolean!
    id: number; // Int!
    text: string; // String!
  }
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  BoolFieldUpdateOperationsInput: NexusGenInputs['BoolFieldUpdateOperationsInput'];
  BoolFilter: NexusGenInputs['BoolFilter'];
  DateTimeFieldUpdateOperationsInput: NexusGenInputs['DateTimeFieldUpdateOperationsInput'];
  NestedBoolFilter: NexusGenInputs['NestedBoolFilter'];
  QueryTodosWhereInput: NexusGenInputs['QueryTodosWhereInput'];
  StringFieldUpdateOperationsInput: NexusGenInputs['StringFieldUpdateOperationsInput'];
  TodoCreateInput: NexusGenInputs['TodoCreateInput'];
  TodoOrderByInput: NexusGenInputs['TodoOrderByInput'];
  TodoUpdateInput: NexusGenInputs['TodoUpdateInput'];
  TodoWhereUniqueInput: NexusGenInputs['TodoWhereUniqueInput'];
  SortOrder: NexusGenEnums['SortOrder'];
  String: NexusGenScalars['String'];
  Int: NexusGenScalars['Int'];
  Float: NexusGenScalars['Float'];
  Boolean: NexusGenScalars['Boolean'];
  ID: NexusGenScalars['ID'];
  DateTime: NexusGenScalars['DateTime'];
}

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createOneTodo: NexusGenRootTypes['Todo']; // Todo!
    deleteOneTodo: NexusGenRootTypes['Todo'] | null; // Todo
    updateOneTodo: NexusGenRootTypes['Todo'] | null; // Todo
  }
  Query: { // field return type
    todo: NexusGenRootTypes['Todo'] | null; // Todo
    todos: NexusGenRootTypes['Todo'][]; // [Todo!]!
  }
  Todo: { // field return type
    completed: boolean; // Boolean!
    id: number; // Int!
    text: string; // String!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneTodo: { // args
      data: NexusGenInputs['TodoCreateInput']; // TodoCreateInput!
    }
    deleteOneTodo: { // args
      where: NexusGenInputs['TodoWhereUniqueInput']; // TodoWhereUniqueInput!
    }
    updateOneTodo: { // args
      data: NexusGenInputs['TodoUpdateInput']; // TodoUpdateInput!
      where: NexusGenInputs['TodoWhereUniqueInput']; // TodoWhereUniqueInput!
    }
  }
  Query: {
    todo: { // args
      where: NexusGenInputs['TodoWhereUniqueInput']; // TodoWhereUniqueInput!
    }
    todos: { // args
      after?: NexusGenInputs['TodoWhereUniqueInput'] | null; // TodoWhereUniqueInput
      before?: NexusGenInputs['TodoWhereUniqueInput'] | null; // TodoWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['TodoOrderByInput'][] | null; // [TodoOrderByInput!]
      where?: NexusGenInputs['QueryTodosWhereInput'] | null; // QueryTodosWhereInput
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Mutation" | "Query" | "Todo";

export type NexusGenInputNames = "BoolFieldUpdateOperationsInput" | "BoolFilter" | "DateTimeFieldUpdateOperationsInput" | "NestedBoolFilter" | "QueryTodosWhereInput" | "StringFieldUpdateOperationsInput" | "TodoCreateInput" | "TodoOrderByInput" | "TodoUpdateInput" | "TodoWhereUniqueInput";

export type NexusGenEnumNames = "SortOrder";

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "DateTime" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: Context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}